### PR TITLE
Support cors

### PR DESCRIPTION
**Pull request by sivchari**
#### What type of PR is this?

/kind feature

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Add "kube-apiserver-cors-allowed-origin" flag to specify cors policy'
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by wzshiming** [comment]
You can use `make update' to update all the files.

**Comment by sivchari** [comment]
@wzshiming 
I think it's so delighted change for users bacause we can control various settings  if the flag like extraArgs of KwokctlConfiguration is added. 
If you sound this feature good, I'd design this flag. Probably the type is like a following.
`--extra-args kube-apiserve='--cors-allowed-origins=*, --xxx=yyy'`.
wdyt?

**Comment by wzshiming** [comment]
> If you sound this feature good, I'd design this flag. Probably the type is like a following.
--extra-args kube-apiserve='--cors-allowed-origins=*, --xxx=yyy'

It looks good, but there are two things that can cause parsing errors, spaces and `,`.

If contains spaces
- --extra-args
- kube-apiserve='--cors-allowed-origins=*,
- --xxx=yyy'

If contains `,`

Some components accept commas as values, for example `--feature-gates <comma-separated 'key=True|False' pairs>`




So I feel it needs to be weakened to the point where it can only pass one value to a component,
And use ComponentPatches https://github.com/kubernetes-sigs/kwok/blob/c3f4f3cd1fe7480830469edfbfdbc7d860047541/pkg/apis/internalversion/kwokctl_configuration_types.go#L53-L57

## example 1

`--extra-args component1=arg1=val1` or `--extra-args=component1=arg1=val1`

equal

```yaml
- name: component1
  extraArgs:
  - key: arg1
    value: val1 
```

## example 2

`--extra-args component1=arg1=val1 --extra-args component1=arg2=val2`

equal

```yaml
- name: component1
  extraArgs:
  - key: arg1
    value: val1 
- name: component1
  extraArgs:
  - key: arg2
    value: val2 
```

**Comment by sivchari** [comment]
It looks so good. Let's move on with it.
So, I'll close this PR and open the new PR about extra args later.
Is it OK ?

**Comment by sivchari** [comment]
@wzshiming

**Comment by wzshiming** [comment]
Sure, thank you for working on this.

**Pull request closed without merging**
