### PR TITLE
fix make build and image

### PR DESCRIPTION
**Pull request by carlory**
image doesn't support darwin. 

/kind bug

### CODE REVIEW

**Comment by carlory** [comment]
```
(⎈ |ik8s01:argocd)➜  kwok git:(make-build-support-m1) make build
GOOS=darwin GOARCH=arm64 go build -ldflags '-X sigs.k8s.io/kwok/pkg/consts.Version=v0.0.1-24-gcdc794f -X sigs.k8s.io/kwok/pkg/consts.KubeVersion=v1.25.3' -o ./bin/darwin/arm64/kwok ./cmd/kwok
GOOS=darwin GOARCH=arm64 go build -ldflags '-X sigs.k8s.io/kwok/pkg/consts.Version=v0.0.1-24-gcdc794f -X sigs.k8s.io/kwok/pkg/consts.KubeVersion=v1.25.3' -o ./bin/darwin/arm64/kwokctl ./cmd/kwokctl
(⎈ |ik8s01:argocd)➜  kwok git:(make-build-support-m1) make image
docker buildx build --tag=/kwok:v0.0.1-24-gcdc794f --platform=linux/amd64 --load -f images/kwok/Dockerfile .
[+] Building 0.0s (0/0)
ERROR: invalid tag "/kwok:v0.0.1-24-gcdc794f": invalid reference format
make: *** [image] Error 1
(⎈ |ik8s01:argocd)➜  kwok git:(make-build-support-m1)
```

Cannot `make image` execute on the macOS ?

cc @wzshiming

**Comment by wzshiming** [comment]
I will improve the document later

Build on Mac
``` bash
BINARY=kwokctl make build
BINARY_PLATFORMS=linux/amd64 BINARY=kwok make cross-build 
make image
```

**Pull request merged**
