### PR TITLE
fix waitForReady no error return

### PR DESCRIPTION
**Pull request by helen-frank**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
waitForReady unable to return error
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by wzshiming — COMMENTED** [review]
This is expected, only the error message is output instead of the immediate end of the poll.

**Comment by helen-frank** [comment]
> This is expected, only the error message is output instead of the immediate end of the poll.

Is it because kwok does not have node at runtime?

**Comment by wzshiming** [comment]
Just waiting for the apiserver to be ready.

**Comment by helen-frank** [comment]
> Just waiting for the apiserver to be ready.

An idea, delete this code

**Comment by wzshiming** [comment]
This is to avoid the controller constantly restarting when the apiserver is not ready

**Comment by helen-frank** [comment]
got it and /close

**Pull request closed without merging**
