### PR TITLE
Fix SC2009 for shellcheck

### PR DESCRIPTION
**Pull request by Songjoy**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Fix SC2009 for shellcheck

#### Which issue(s) this PR fixes:
xref https://github.com/kubernetes-sigs/kwok/issues/470

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by wzshiming — APPROVED** [review]

**Comment by wzshiming** [comment]
> Error: '-v' flag not exsits in kube-apiserver

https://github.com/kubernetes-sigs/kwok/blob/ec2c1f2df21f1f9b7b38aa1e5456cf48b6724690/test/kwokctl/kwokctl_verbosity_test.sh#L108

/cc @Zhuzhenghao

Looks like a bug was caught

**Comment by Zhuzhenghao** [comment]
I will work on it.

**Comment by wzshiming** [comment]
/hold
Waiting to fix the bug

**Comment by Zhuzhenghao** [comment]
ref #503

**Review by Zhuzhenghao — APPROVED** [review]

**Pull request merged**
