### PR TITLE
Set/remove current-context after cluster create/deletion

### LINKED ISSUE #320: [kwokctl] set/remove `current-context` after cluster create/deletion
### What would you like to be added?

When a user creates a cluster using `kwokctl`, it's better to automatically switch the `current-context` to the newly created one.

```
⇒  k ctx -c
kwok-k2

⇒  kwokctl create cluster --name k3
...
Cluster is created                                                                                                                               cluster=k3 elapsed=1s
You can now use your cluster with:

    kubectl config use-context kwok-k3

Thanks for using kwok!

⇒  k ctx -c
kwok-k2 <- I'd expect it switches to kwok-k3 automatically
```

The same story applies to cluster deletion. I'd like to unset the current-context.

### Why is this needed?

For better UX. When a user creates/deletes a cluster, their instinct is to use/not use that cluster right away.

### PR DESCRIPTION
**Pull request by qihuang0**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
With this commit， we can set/remove current-context after cluster create/deletion

#### Which issue(s) this PR fixes:

Fixes #320 

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by wzshiming** [comment]
Hi, do you have time to continue this work, I intend to take it forward.

**Comment by qihuang0** [comment]
> Hi, do you have time to continue this work, I intend to take it forward.

I'm sorry, but I've been really busy lately and have decided to give up this work

**Pull request closed without merging**
