### PR TITLE
[kwokctl] support all feature-gates

### PR DESCRIPTION
**Pull request by JarHMJ**
#### What type of PR is this?
/kind feature

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by wzshiming — COMMENTED** [review]
Add a case in ci `.github/workflows/test.yaml`

``` yaml
      - name: Test Mode StableFeatureGateAndAPI
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.kwokctl-runtime == 'binary' }}
        shell: bash
        env:
          LAST_RELEASE_SIZE: 20
          KWOK_MODE: StableFeatureGateAndAPI
        run: |
          ./hack/e2e-test.sh kwokctl/kwokctl_${{ matrix.kwokctl-runtime }}
```

**Comment by JarHMJ** [comment]
> 

done

**Review by wzshiming — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
