### PR TITLE
Add Yibo to OWNERS

### PR DESCRIPTION
**Pull request by Huang-Wei**
Yibo helped a lot during incubating this project.

### CODE REVIEW

**Comment by wzshiming** [comment]
One way to make the user trusted is to add them as [members](https://git.k8s.io/community/community-membership.md#member) of the kubernetes-sigs org.

/lgtm
/hold

Maybe it should be left to trigger after Yibo becomes a member, in case something goes wrong with the automation process `/unhold`

**Comment by wzshiming** [comment]
/unhold

It seems that my fears were superfluous which has been taken into account `do-not-merge/invalid-owners-file`

**Comment by Huang-Wei** [comment]
@wzshiming you're right, @yibozhuang is working on a k8s member request.

**Review by wzshiming — APPROVED** [review]

**Pull request merged**
