### PR TITLE
Correct grammar about using 'exec'

### PR DESCRIPTION
**Pull request by network-charles**
#### What type of PR is this?

/kind cleanup
/kind documentation

#### What this PR does / why we need it:
While learning to use the `exec` feature, I realized some sentences have preposition issues. Prepositions use words like at, in, on, etc. to describe where things are, or how something is used. The sentences didn't describe how the noun "information" is used on a local target. 

I added "on" before "how" to correct this.

#### Does this PR introduce a user-facing change?

```release-note
Sentences containing "information how to" have been removed and updated to "information on how to".
```

### CODE REVIEW

**Comment by wzshiming** [comment]
Should other APIs have the same problem and can you help to correct it together?

**Comment by network-charles** [comment]
Yes, they do. I'll correct it and update the release note.

**Comment by network-charles** [comment]
@wzshiming, I don't know why the test is failing. Let me know what you think, so I can decide if I will create a separate PR for my last commit or not.

**Comment by wzshiming** [comment]
Need run `./hack/update-controllergen.sh` to update CRD

**Comment by network-charles** [comment]
Oh! Could it be because we are committing new contents to files in this folder on the script `${ROOT_DIR}/kustomize/crd/bases`?

**Comment by wzshiming** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kwok/1074/pull-kwok-verify-main/1789979642556321792

Yes, the CRD is maintained by the automatic, and the changes you make are inconsistent with it.

**Comment by network-charles** [comment]
It seems the test keeps failing even after I discarded the previous commit and created a new one. I'll delete this branch and try again with a new branch.

**Pull request closed without merging**
