### PR TITLE
fix: Cannot compile in bash 3.2

### LINKED ISSUE #177: Cannot compile in bash 3.2.x
### How to use it?

- [ ] kwok
- [ ] kwokctl --runtime=docker (default runtime)
- [ ] kwokctl --runtime=binary
- [ ] kwokctl --runtime=nerdctl
- [ ] kwokctl --runtime=kind

### What happened?

image

### What did you expect to happen?

Can compile.

### How can we reproduce it (as minimally and precisely as possible)?

1. Mac m1
2. GNU bash, version 3.2.57(1)-release-(arm64-apple-darwin22) 
3. make build

### Anything else we need to know?

https://github.com/kubernetes-sigs/kwok/blob/483e9d7e71acd8ec4ab38d12510b7bc55153b18c/hack/get-platform.sh#L45

Only bash version 4.0 or above is supported.

### OS version

<details>
```console        
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Darwin:
$ uname -a
Darwin chauncey-2.local 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103 arm64

GNU bash, version 3.2.57(1)-release-(arm64-apple-darwin22)

# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### PR DESCRIPTION
**Pull request by chaunceyjiang**
Signed-off-by: chaunceyjiang <chaunceyjiang@gmail.com>

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
compile kwok in bash 3.2.

#### Which issue(s) this PR fixes:

Fixes #177 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by chaunceyjiang** [comment]
image

**Comment by wzshiming** [comment]
Need rebase to latest

**Review by wzshiming — APPROVED** [review]

**Pull request merged**
