### PR TITLE
add Aptakube adopter + blogpost

### PR DESCRIPTION
**Pull request by goenning**
#### What type of PR is this?

/kind documentation

#### Which issue(s) this PR fixes:

N/A

#### Special notes for your reviewer:

N/A

#### Does this PR introduce a user-facing change?

No

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

N/A

### CODE REVIEW

**Comment by wzshiming** [comment]
/ok-to-test
/release-note-node

Amazing work

**Comment by goenning** [comment]
Thanks @wzshiming

Seems like an unrelated test is breaking? Is that a known issue?

**Comment by wzshiming** [comment]
never mind, it is a flake test.

**Pull request merged**
