### PR TITLE
Revert "[kwokctl] Update start/stop for nerdctl"

### PR DESCRIPTION
**Pull request by zwpaper**
Reverts kubernetes-sigs/kwok#249

### CODE REVIEW

**Comment by wzshiming** [comment]
It doesn't look like that's the problem?

**Comment by wzshiming** [comment]
The #258 tests all pass, and it seems that some unstable behavior of nerdctl is the cause.

**Comment by zwpaper** [comment]
it is due to the unstable behavior of `nerdctl stop`:

I build up a cluster:

image

then stop it, it disappears for a while, but reappears seconds later, and the containers up-time keep growing up

image


the test results differ because the difference of containers' disappear time is different each time we call `kwokctl stop cluster`

**Comment by wzshiming** [comment]
Good job.

In fact, the old nerdctl's restart test was also so unstable that I thought we'd add a check to wait for its complete shutdown. wdyt?

**Comment by zwpaper** [comment]
> I thought we'd add a check to wait for its complete shutdown
of cause, will raise a PR after checking the `nerdctl compose stop`

**Comment by zwpaper** [comment]
this is confirmed to a bug, should we let this PR continue? @wzshiming 

https://github.com/containerd/nerdctl/issues/1980#issuecomment-1420715781

**Comment by wzshiming** [comment]
Thanks!

/approve
/lgtm

**Review by wzshiming — APPROVED** [review]

**Pull request merged**
